# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'MyTestApp' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for MyTestApp
  pod 'Firebase/Core'
  pod 'Firebase/Auth'
  pod 'FirebaseUI'
  pod 'Firebase/Database'
  pod 'Firebase/Storage'
end
